version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gomoddirectives
    - gomodguard
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unparam
    - zerologlint
    - revive

  disable:
    # preset error
    # These should probably be cleaned up at some point if we want to publish part of this as a library.
    - err113 # Very annoying to define static errors everywhere
    - wrapcheck # Very annoying to wrap errors everywhere
    # preset import
    - depguard

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
