name: 'releaser-pleaser'
description: 'automated releases based on conventional commits'
author: Julian Tölle
branding:
  icon: 'package'
  color: 'red'
inputs:
  # Remember to update docs/reference/github-action.md
  branch:
    default: main
    description: "This branch is used as the target for releases."
  token:
    description: 'GitHub token for creating and updating release PRs, defaults to using secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  extra-files:
    description: 'List of files that are scanned for version references by the generic updater.'
    required: false
    default: ""
  updaters:
    description: "List of updaters that are run. Default updaters can be removed by specifying them as -name. Multiple updaters should be concatenated with a comma. Default Updaters: changelog,generic"
    required: false
    default: ""
  # Remember to update docs/reference/github-action.md
outputs: { }
runs:
  using: 'docker'
  image: docker://ghcr.io/apricote/releaser-pleaser:v0.7.0 # x-releaser-pleaser-version
  args:
    - run
    - --forge=github
    - --branch=${{ inputs.branch }}
    - --extra-files="${{ inputs.extra-files }}"
    - --updaters="${{ inputs.updaters }}"
  env:
    GITHUB_TOKEN: "${{ inputs.token }}"
    GITHUB_USER: "oauth2"
