[book]
language = "en"
src = "."
title = "releaser-pleaser"

[output.html]
git-repository-url = "https://github.com/apricote/releaser-pleaser"
edit-url-template = "https://github.com/apricote/releaser-pleaser/edit/main/docs/{path}"
