name: Conventional Commits Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  check-conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check Semantic Pull Request title
        uses: amannn/action-semantic-pull-request@v6
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
