name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3

      - name: Prepare ko
        run: |
          echo "${{ github.token }}" | ko login ghcr.io --username "dummy" --password-stdin

          repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "KO_DOCKER_REPO=ghcr.io/${repo}"
          echo "KO_DOCKER_REPO=ghcr.io/${repo}" >> $GITHUB_ENV

      - run: ko build --bare --tags ${{ github.ref_name }} github.com/apricote/releaser-pleaser/cmd/rp
